In [50]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [41]:
webpage = requests.get('https://books.toscrape.com/catalogue/page-1.html').text

In [17]:
soup = BeautifulSoup(webpage, 'lxml')

In [18]:
print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [40]:
books = soup.find_all('article', class_='product_pod')

In [42]:
len(books)

20

In [20]:
for i in soup.find_all('h3'):
    print(i.text.strip())

A Light in the ...
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History ...
The Requiem Red
The Dirty Little Secrets ...
The Coming Woman: A ...
The Boys in the ...
The Black Maria
Starving Hearts (Triangular Trade ...
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little ...
Rip it Up and ...
Our Band Could Be ...
Olio
Mesaerion: The Best Science ...
Libertarianism for Beginners
It's Only the Himalayas

In [21]:
for i in  soup.find_all('p'):
    print(i.text.strip())

Â£51.77
In stock

Â£53.74
In stock

Â£50.10
In stock

Â£47.82
In stock

Â£54.23
In stock

Â£22.65
In stock

Â£33.34
In stock

Â£17.93
In stock

Â£22.60
In stock

Â£52.15
In stock

Â£13.99
In stock

Â£20.66
In stock

Â£17.46
In stock

Â£52.29
In stock

Â£35.02
In stock

Â£57.25
In stock

Â£23.88
In stock

Â£37.59
In stock

Â£51.33
In stock

Â£45.17
In stock

In [23]:
for i in soup.find_all('p',class_='price_color'):
    print(i.text.strip())

Â£51.77
Â£53.74
Â£50.10
Â£47.82
Â£54.23
Â£22.65
Â£33.34
Â£17.93
Â£22.60
Â£52.15
Â£13.99
Â£20.66
Â£17.46
Â£52.29
Â£35.02
Â£57.25
Â£23.88
Â£37.59
Â£51.33
Â£45.17

In [25]:
for i in soup.find_all('p',class_='instock availability'):
    print(i.text.strip())

In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock

In [27]:
for i in soup.find_all('p',class_='star-rating'):
    print(i.get('class')[1])

Three
One
One
Four
Five
One
Four
Three
Four
One
Two
Four
Five
Five
Five
Three
One
One
Two
Two

In [68]:
name=[]
price=[]
availability=[]
rating=[]

In [69]:
for i in books:
    name.append(i.find('h3').find('a').get('title'))
    price.append(i.find('p',class_='price_color').text.strip())
    availability.append(i.find('p',class_='instock availability').get_text(strip=True))
    rating.append(i.find('p',class_='star-rating').get('class')[1])
df=pd.DataFrame({
    'name':name,
    'price':price,
    'availability':availability,
    'rating':rating
})

In [66]:
len(name),len(price),len(availability),len(rating)

(80, 80, 80, 80)

In [70]:
df.head()

                                    name    price availability rating
0                   A Light in the Attic  Â£51.77     In stock  Three
1                     Tipping the Velvet  Â£53.74     In stock    One
2                             Soumission  Â£50.10     In stock    One
3                          Sharp Objects  Â£47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock   Five

In [72]:
df.shape

(20, 4)

In [74]:
df.columns

Index(['name', 'price', 'availability', 'rating'], dtype='str')

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          20 non-null     str
 1   price         20 non-null     str
 2   availability  20 non-null     str
 3   rating        20 non-null     str
dtypes: str(4)
memory usage: 1.8 KB

In [76]:
df.describe()

                        name    price availability rating
count                     20       20           20     20
unique                    20       20            1      5
top     A Light in the Attic  Â£51.77     In stock    One
freq                       1        1           20      6

In [81]:
df['price'] = df['price'].str.extract(r'([\d.]+)').astype(float)

In [82]:
df.head()

                                    name  price availability rating
0                   A Light in the Attic  51.77     In stock  Three
1                     Tipping the Velvet  53.74     In stock    One
2                             Soumission  50.10     In stock    One
3                          Sharp Objects  47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  54.23     In stock   Five

In [83]:
df.describe()

           price
count  20.000000
mean   38.048500
std    15.135231
min    13.990000
25%    22.637500
50%    41.380000
75%    51.865000
max    57.250000

In [85]:
rating_map={
    'One':1,
    'Two':2,
     'Three': 3,
    'Four': 4,
    'Five': 5
}
df['rating']=df['rating'].map(rating_map)

In [86]:
df.head()

                                    name  price availability  rating
0                   A Light in the Attic  51.77     In stock       3
1                     Tipping the Velvet  53.74     In stock       1
2                             Soumission  50.10     In stock       1
3                          Sharp Objects  47.82     In stock       4
4  Sapiens: A Brief History of Humankind  54.23     In stock       5

In [87]:
df.sort_values('rating',ascending=False).head()

,name,price,availability,rating
12,Set Me Free,17.46,In stock,5
4,Sapiens: A Brief History of Humankind,54.23,In stock,5
14,Rip it Up and Start Again,35.02,In stock,5
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock,5
3,Sharp Objects,47.82,In stock,4

In [88]:
df.sort_values('price').head()

,name,price,availability,rating
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,In stock,2
12,Set Me Free,17.46,In stock,5
7,The Coming Woman: A Novel Based on the Life of...,17.93,In stock,3
11,Shakespeare's Sonnets,20.66,In stock,4
8,The Boys in the Boat: Nine Americans and Their...,22.60,In stock,4

In [90]:
df.sort_values('price',ascending=False).head()

,name,price,availability,rating
15,Our Band Could Be Your Life: Scenes from the A...,57.25,In stock,3
4,Sapiens: A Brief History of Humankind,54.23,In stock,5
1,Tipping the Velvet,53.74,In stock,1
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,In stock,5
9,The Black Maria,52.15,In stock,1

In [93]:
df.groupby('rating')['price'].mean()

rating
1    40.018333
2    36.830000
3    42.316667
4    31.105000
5    39.750000
Name: price, dtype: float64

In [94]:
df['rating'].value_counts().sort_index()

rating
1    6
2    3
3    3
4    4
5    4
Name: count, dtype: int64

In [95]:
df['availability'].value_counts()

availability
In stock    20
Name: count, dtype: int64

In [96]:
final=pd.DataFrame()

for page in range(1,51):
    url = f'https://books.toscrape.com/catalogue/page-{page}.html'
    webpage=requests.get(url).text
    soup=BeautifulSoup(webpage,'lxml')
    books=soup.find_all('article',class_='product_pod')

    name=[]
    price=[]
    availability=[]
    rating=[]

    for i in books:
        name.append(i.find('h3').find('a').get('title'))
        price.append(i.find('p',class_='price_color').text.strip())
        availability.append(i.find('p',class_='instock availability').get_text(" ",strip=True))
        rating.append(i.find('p',class_='star-rating').get('class')[1])

    temp=pd.DataFrame({
            'name':name,
            'price':price,
            'availability':availability,
            'rating':rating
        })
    final=pd.concat([final,temp],ignore_index=True)

In [97]:
final.shape

(1000, 4)

In [98]:
final.head()

                                    name    price availability rating
0                   A Light in the Attic  Â£51.77     In stock  Three
1                     Tipping the Velvet  Â£53.74     In stock    One
2                             Soumission  Â£50.10     In stock    One
3                          Sharp Objects  Â£47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock   Five

In [99]:
final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          1000 non-null   str
 1   price         1000 non-null   str
 2   availability  1000 non-null   str
 3   rating        1000 non-null   str
dtypes: str(4)
memory usage: 89.9 KB

In [100]:
final['price'] = final['price'].str.extract(r'([\d.]+)').astype(float)

In [101]:
final.head()

                                    name  price availability rating
0                   A Light in the Attic  51.77     In stock  Three
1                     Tipping the Velvet  53.74     In stock    One
2                             Soumission  50.10     In stock    One
3                          Sharp Objects  47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  54.23     In stock   Five

In [102]:
rating_map={
     'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5
}
final['rating']=final['rating'].map(rating_map)

In [103]:
final.head()

                                    name  price availability  rating
0                   A Light in the Attic  51.77     In stock       3
1                     Tipping the Velvet  53.74     In stock       1
2                             Soumission  50.10     In stock       1
3                          Sharp Objects  47.82     In stock       4
4  Sapiens: A Brief History of Humankind  54.23     In stock       5

In [106]:
final.tail()

,name,price,availability,rating
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,In stock,1
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,In stock,4
997,A Spy's Devotion (The Regency Spies of London #1),16.97,In stock,5
998,1st to Die (Women's Murder Club #1),53.98,In stock,1
999,"1,000 Places to See Before You Die",26.08,In stock,5

In [104]:
final.describe()

            price       rating
count  1000.00000  1000.000000
mean     35.07035     2.923000
std      14.44669     1.434967
min      10.00000     1.000000
25%      22.10750     2.000000
50%      35.98000     3.000000
75%      47.45750     4.000000
max      59.99000     5.000000

In [105]:
final.columns

Index(['name', 'price', 'availability', 'rating'], dtype='str')

In [107]:
final.dtypes

name                str
price           float64
availability        str
rating            int64
dtype: object

In [108]:
final.isnull().sum()

name            0
price           0
availability    0
rating          0
dtype: int64

In [109]:
final.isnull().sum().sum()

np.int64(0)

In [110]:
final.isnull().sum().sum()

np.int64(0)